# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-17 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('meals_id', models.IntegerField(primary_key=True, serialize=False)),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.Food')),
            ],
        ),
    ]
