# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_food_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='meals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postings.Meals'),
            preserve_default=False,
        ),
    ]
