# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20190918_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meals',
        ),
        migrations.AddField(
            model_name='meals',
            name='foods',
            field=models.ManyToManyField(to='postings.Food'),
        ),
    ]
