# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-18 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_auto_20190918_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
