# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_auto_20190918_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_food', models.ManyToManyField(to='postings.Food')),
            ],
        ),
    ]
