# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-18 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_auto_20190918_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='The_food_available_meals_are',
            new_name='Meals_and_Foods',
        ),
    ]
